# Don't print a new line at the start of the prompt
add_newline = false

right_format = "$time"
# Replace the "â¯" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[â¯](bold #ffaf00)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
error_symbol = "[â¯](bold 202)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"
#vicmd_symbol = "[Vi](bold 155)"
vicmd_symbol = "[â®](bold 155)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
format = "[$path ](bold #ffd700)"

[time]
disabled = false
use_12hr = true

[localip]
disabled = true

#[env_var.SSH_CONNECTION]
#variable = "SSH_CONNECTION"


[sudo]
disabled = true
symbol = "ğŸ§™ "
